### PR TITLE
Fancy <abbr> tag

### PR DESCRIPTION
**Pull request by gjvnq**
Added CSS to allow for fancy usage of the <abbr> tag. Also added JS to show the term definition on click so that mobile users aren't left out.

Screen Shot 2022-05-30 at 11 41 27

### CODE REVIEW

**Comment by ErdaradunGaztea** [comment]
Ooooh, I like this one! Would use a lot for Polish translation, since we don't even have an abbreviation like AFAB/AMAB, so it's "o męskiej/żeńskiej płci przypisanej przy urodzeniu" everywhere and that's kinda long. I can volunteer to help with placing these in text (clean up some AFAB/AMAB placements, add HRT and others) if the proposal is accepted :)

I worry a little about printing GDB pages, since it's hard to print tooltips. Not to say it's a problem, I can see four more or less feasible solutions to that:

- ignore completely
- insert tooltips as text inside parentheses after the abbreviation (e.g. "AFAB (assigned female at birth)"); it could spam the text with abbreviations though, especially for constantly used AFABs/AMABs, though
- add (manually written) "Dictionary" section as, say, the last or the second chapter (reasonably comfortable to use when printed)
- insert footnotes (which will probably still be placed at the end when printing e.g. "View All" page, so not much difference to "Dictionary" section)

**Comment by gjvnq** [comment]
A glossary would be the best. However, of the abbreviations are explained
when first introduced, the text as a whole is still readable without the
tooltips.

Em seg., 30 de mai. de 2022 12:22, Laura Bąkała ***@***.***>
escreveu:

**Comment by Twipped** [comment]
This is something I've been wanting to do for a long time, but wanted to automate it against a proper glossary catalog.
There *is* an ABBR plugin for markdown-it that we could tie in. https://github.com/markdown-it/markdown-it-abbr

**Comment by gjvnq** [comment]
> This is something I've been wanting to do for a long time, but wanted to automate it against a proper glossary catalog. There is an ABBR plugin for markdown-it that we could tie in. https://github.com/markdown-it/markdown-it-abbr

That is great and will probaby make the whole thing easier.

**Comment by gjvnq** [comment]
This pull request is unecessary if #100 is merged,

**Comment by Twipped** [comment]
Closing this in favor of #100.

**Pull request closed without merging**
