### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by adeeena**
new translation: Hungarian (Magyar)

- I'm getting external review of other Hungarians, **corrective pull requests might arrive soon**
- Some fonts used on the page has no character typeface for each Hungarian letters: "ő", "ű" and their uppercase versions render badly. I used substitute letters, still easily readable for any Hungarian though.
- Few images rewritten for Hungarian text (remark: as there were no indication of what font was used, I picked ones with similar style, but maybe for the further translators it might be helpful to have a template/ttf/guide provided)
- Half of wiki links point to the Hungarian version, but most of them are simply not translated, I'll look around the internet to find Hungarian resources for external links if possible.
- No PDF was made from my translation -- is there any way of concatenating it nicely? Will you do it?
- Is there any way to display the translator name somewhere in the translated page?

Thanks!

### CODE REVIEW

**Comment by adeeena** [comment]
> About these fonts, I encountered the same problem with German and Polish translations, so there's a SCSS file (`scss/_font-compatibility.scss`) that uses some other font (one of the default ones, that have characters for most languages) with languages specified. You can add Hungarian in there instead of using substitute letters, if you want :)
> 
> (just modify a line to say `html[lang=de], html[lang=hu]` instead of `html[lang=de]`, should be enough)

I tried applying the changes in the file provided, but the result is sadly less satisfying than before. I keep my pull request as is.

**Comment by ErdaradunGaztea** [comment]
I think there is one thing missing, shouldn't you include Hungarian `_concat.json` file in `build/_concats.js`? I might be wrong about that, obviously.

**Comment by adeeena** [comment]
> I think there is one thing missing, shouldn't you include Hungarian `_concat.json` file in `build/_concats.js`? I might be wrong about that, obviously.

Nice catch! Although in that case, the `contributing.md` file should also be updated for all these remarks.

**Comment by ErdaradunGaztea** [comment]
It's a recent development, that's why it's missing. But I was thinking about updating it with my experience translating, I guess I'll have some time now that we finished Polish translation ("lost" with you by mere 6 hours xd).

**Comment by adeeena** [comment]
> ("lost" with you by mere 6 hours xd).

I'm sorry, I was not aware we are competing.

**Comment by Twipped** [comment]
> Few images rewritten for Hungarian text (remark: as there were no indication of what font was used, I picked ones with similar style, but maybe for the further translators it might be helpful to have a template/ttf/guide provided)

Font isn't all that important. Many of the images were sourced around the web. The main site logo is made in Acorn, and the file for it is in /resources. https://github.com/GenderDysphoria/GenderDysphoria.fyi/blob/master/resources/gdb.acorn
I've gone ahead and produced new titlecards for both this and the polish translation.

> No PDF was made from my translation -- is there any way of concatenating it nicely? Will you do it?

The PDFs are all WAY behind, I need to create an automated process for generating them, it's too much of a pain to do it by hand. I'm basically just exporting the print concat version as a PDF from a browser.

> Is there any way to display the translator name somewhere in the translated page?

Absolutely, we can put it on the introduction page in the sidebar. What name would you like?" Same for you, @ErdaradunGaztea

**Comment by adeeena** [comment]
I would prefer showing my full name, "Adéna Muráncsik" if possible.

Although maybe on the introduction page, for the markdown you could pick that value from a metadata tag, wouldn't it be more versatile?

**Comment by ErdaradunGaztea** [comment]
"Laura Bąkała". Though I worry that adding translators' names might run into the same set of issues as "authoring" a Wikipedia article. I had a little help with translation, for example, where one person translated chapters 4 & 8, and the other did the intro.

**Pull request merged**
